services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # PgAdmin for DB management.
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  pgdata: {}
  pgadmin-data: {}

  # DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
